sonar.projectKey=kingg22_debida-diligencia-reforzada
sonar.organization=kingg22
sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/alembic/versions/**
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
