// This file is auto-generated by @hey-api/openapi-ts

export const AprobacionInputSchema = {
    properties: {
        observaciones: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observaciones'
        }
    },
    type: 'object',
    title: 'AprobacionInput'
} as const;

export const AsignarAnalistaInputSchema = {
    properties: {
        analista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Analista Id'
        }
    },
    type: 'object',
    required: ['analista_id'],
    title: 'AsignarAnalistaInput'
} as const;

export const AuditoriaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        usuario_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Usuario Id'
        },
        usuario_nombre: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Usuario Nombre'
        },
        modulo: {
            type: 'string',
            title: 'Modulo'
        },
        accion: {
            type: 'string',
            title: 'Accion'
        },
        entidad_tipo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entidad Tipo'
        },
        entidad_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entidad Id'
        },
        descripcion: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descripcion'
        },
        ip_origen: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Origen'
        },
        creado_en: {
            type: 'string',
            format: 'date-time',
            title: 'Creado En'
        }
    },
    type: 'object',
    required: ['id', 'usuario_id', 'modulo', 'accion', 'entidad_tipo', 'entidad_id', 'descripcion', 'ip_origen', 'creado_en'],
    title: 'AuditoriaPublic'
} as const;

export const AuditoriasPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditoriaPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditoriasPublic'
} as const;

export const BeneficiarioFinalCreateSchema = {
    properties: {
        nombre: {
            type: 'string',
            maxLength: 100,
            title: 'Nombre'
        },
        apellido: {
            type: 'string',
            maxLength: 100,
            title: 'Apellido'
        },
        cedula: {
            type: 'string',
            maxLength: 50,
            title: 'Cedula'
        },
        nacionalidad: {
            type: 'string',
            maxLength: 80,
            title: 'Nacionalidad'
        },
        pais: {
            type: 'string',
            maxLength: 80,
            title: 'Pais'
        },
        fecha_nacimiento: {
            type: 'string',
            maxLength: 20,
            title: 'Fecha Nacimiento'
        },
        porcentaje_participacion: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Porcentaje Participacion',
            default: 0
        },
        es_pep: {
            type: 'boolean',
            title: 'Es Pep',
            default: false
        }
    },
    type: 'object',
    required: ['nombre', 'apellido', 'cedula', 'nacionalidad', 'pais', 'fecha_nacimiento'],
    title: 'BeneficiarioFinalCreate'
} as const;

export const BeneficiarioFinalPublicSchema = {
    properties: {
        nombre: {
            type: 'string',
            maxLength: 100,
            title: 'Nombre'
        },
        apellido: {
            type: 'string',
            maxLength: 100,
            title: 'Apellido'
        },
        cedula: {
            type: 'string',
            maxLength: 50,
            title: 'Cedula'
        },
        nacionalidad: {
            type: 'string',
            maxLength: 80,
            title: 'Nacionalidad'
        },
        pais: {
            type: 'string',
            maxLength: 80,
            title: 'Pais'
        },
        fecha_nacimiento: {
            type: 'string',
            maxLength: 20,
            title: 'Fecha Nacimiento'
        },
        porcentaje_participacion: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Porcentaje Participacion',
            default: 0
        },
        es_pep: {
            type: 'boolean',
            title: 'Es Pep',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['nombre', 'apellido', 'cedula', 'nacionalidad', 'pais', 'fecha_nacimiento', 'id'],
    title: 'BeneficiarioFinalPublic'
} as const;

export const Body_casos_ddr_upload_documento_ddrSchema = {
    properties: {
        tipo: {
            '$ref': '#/components/schemas/DocumentoTipo'
        },
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['tipo', 'file'],
    title: 'Body_casos-ddr-upload_documento_ddr'
} as const;

export const Body_clientes_upload_documentoSchema = {
    properties: {
        tipo: {
            '$ref': '#/components/schemas/DocumentoTipo'
        },
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['tipo', 'file'],
    title: 'Body_clientes-upload_documento'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CasoDDRPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        expediente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Expediente Id'
        },
        nivel_riesgo: {
            type: 'string',
            title: 'Nivel Riesgo'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        analista_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Analista Id'
        },
        aprobado_por_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aprobado Por Id'
        },
        observaciones_rechazo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observaciones Rechazo'
        },
        fecha_apertura: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fecha Apertura'
        },
        fecha_cierre: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fecha Cierre'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        cliente: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ClienteResumen'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'expediente_id', 'nivel_riesgo', 'status'],
    title: 'CasoDDRPublic'
} as const;

export const CasosDDRPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CasoDDRPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CasosDDRPublic'
} as const;

export const ClientTypeSchema = {
    type: 'string',
    enum: ['NATURAL', 'JURIDICA'],
    title: 'ClientType'
} as const;

export const ClienteResumenSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        codigo: {
            type: 'string',
            title: 'Codigo'
        },
        tipo_cliente: {
            type: 'string',
            title: 'Tipo Cliente'
        },
        nombres: {
            type: 'string',
            title: 'Nombres'
        },
        apellidos: {
            type: 'string',
            title: 'Apellidos'
        },
        tipo_identificacion: {
            type: 'string',
            title: 'Tipo Identificacion'
        },
        numero_identificacion: {
            type: 'string',
            title: 'Numero Identificacion'
        },
        nivel_riesgo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nivel Riesgo'
        },
        estado: {
            type: 'string',
            title: 'Estado'
        },
        es_pep: {
            type: 'boolean',
            title: 'Es Pep',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'codigo', 'tipo_cliente', 'nombres', 'apellidos', 'tipo_identificacion', 'numero_identificacion', 'estado'],
    title: 'ClienteResumen',
    description: `Proyección mínima de un expediente KYC para embeber en otras
respuestas (casos DDR, dashboard, etc.) y evitar un round-trip extra.
Mantener sincronizado con la vista \`\`Cliente\`\` del frontend.`
} as const;

export const CuestionarioEBRPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        caso_ddr_id: {
            type: 'string',
            format: 'uuid',
            title: 'Caso Ddr Id'
        },
        origen_fondos: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Origen Fondos'
        },
        proposito_relacion: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proposito Relacion'
        },
        patrimonio_estimado: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patrimonio Estimado'
        },
        pais_origen_patrimonio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pais Origen Patrimonio'
        },
        tiene_estructura_societaria: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tiene Estructura Societaria'
        },
        familiar_pep: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Familiar Pep'
        },
        completado: {
            type: 'boolean',
            title: 'Completado',
            default: false
        },
        completado_por: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completado Por'
        },
        completado_en: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completado En'
        }
    },
    type: 'object',
    required: ['id', 'caso_ddr_id'],
    title: 'CuestionarioEBRPublic'
} as const;

export const CuestionarioUpdateSchema = {
    properties: {
        origen_fondos: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Origen Fondos'
        },
        proposito_relacion: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proposito Relacion'
        },
        patrimonio_estimado: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patrimonio Estimado'
        },
        pais_origen_patrimonio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pais Origen Patrimonio'
        },
        tiene_estructura_societaria: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tiene Estructura Societaria'
        },
        familiar_pep: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Familiar Pep'
        }
    },
    type: 'object',
    title: 'CuestionarioUpdate'
} as const;

export const DocumentoEstadoSchema = {
    type: 'string',
    enum: ['PENDIENTE', 'VALIDADO', 'RECHAZADO'],
    title: 'DocumentoEstado'
} as const;

export const DocumentoKYCPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        expediente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Expediente Id'
        },
        caso_ddr_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Caso Ddr Id'
        },
        tipo: {
            '$ref': '#/components/schemas/DocumentoTipo'
        },
        nombre: {
            type: 'string',
            title: 'Nombre'
        },
        tamanio: {
            type: 'integer',
            title: 'Tamanio'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        estado: {
            '$ref': '#/components/schemas/DocumentoEstado'
        },
        hash_sha256: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hash Sha256'
        },
        fecha_carga: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fecha Carga'
        }
    },
    type: 'object',
    required: ['id', 'expediente_id', 'tipo', 'nombre', 'tamanio', 'mime_type', 'estado'],
    title: 'DocumentoKYCPublic'
} as const;

export const DocumentoTipoSchema = {
    type: 'string',
    enum: ['CEDULA_FRONTAL', 'CEDULA_POSTERIOR', 'PASAPORTE', 'RUC', 'REGISTRO_MERCANTIL', 'ESTADOS_FINANCIEROS', 'DECLARACION_RENTA', 'ESCRITURA_CONSTITUCION', 'PODER_REPRESENTANTE', 'OTRO'],
    title: 'DocumentoTipo'
} as const;

export const DocumentosDDRPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DocumentoKYCPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DocumentosDDRPublic'
} as const;

export const EstadoCasoDDRSchema = {
    type: 'string',
    enum: ['ABIERTO', 'EN_REVISION', 'EN_APROBACION', 'APROBADO', 'RECHAZADO'],
    title: 'EstadoCasoDDR'
} as const;

export const ExpedienteKYCCreateSchema = {
    properties: {
        tipo_cliente: {
            '$ref': '#/components/schemas/ClientType'
        },
        persona_natural: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PersonaNaturalCreate'
                },
                {
                    type: 'null'
                }
            ]
        },
        persona_juridica: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PersonaJuridicaCreate'
                },
                {
                    type: 'null'
                }
            ]
        },
        beneficiarios_final: {
            items: {
                '$ref': '#/components/schemas/BeneficiarioFinalCreate'
            },
            type: 'array',
            title: 'Beneficiarios Final'
        },
        enviar_a_revision: {
            type: 'boolean',
            title: 'Enviar A Revision',
            default: false
        }
    },
    type: 'object',
    required: ['tipo_cliente'],
    title: 'ExpedienteKYCCreate'
} as const;

export const ExpedienteKYCPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        codigo: {
            type: 'string',
            title: 'Codigo'
        },
        tipo_cliente: {
            '$ref': '#/components/schemas/ClientType'
        },
        status: {
            '$ref': '#/components/schemas/KYCStatus'
        },
        nivel_riesgo: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RiskLevel'
                },
                {
                    type: 'null'
                }
            ]
        },
        puntaje_riesgo: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Puntaje Riesgo'
        },
        comentario_rechazo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comentario Rechazo'
        },
        analista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Analista Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        persona_natural: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PersonaNaturalPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        persona_juridica: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PersonaJuridicaPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        beneficiarios_final: {
            items: {
                '$ref': '#/components/schemas/BeneficiarioFinalPublic'
            },
            type: 'array',
            title: 'Beneficiarios Final'
        },
        documentos: {
            items: {
                '$ref': '#/components/schemas/DocumentoKYCPublic'
            },
            type: 'array',
            title: 'Documentos'
        }
    },
    type: 'object',
    required: ['id', 'codigo', 'tipo_cliente', 'status', 'analista_id'],
    title: 'ExpedienteKYCPublic'
} as const;

export const ExpedienteKYCUpdateSchema = {
    properties: {
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/KYCStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        comentario_rechazo: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comentario Rechazo'
        }
    },
    type: 'object',
    title: 'ExpedienteKYCUpdate'
} as const;

export const ExpedientesKYCPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExpedienteKYCPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExpedientesKYCPublic'
} as const;

export const FactorRiesgoSchema = {
    properties: {
        factor: {
            type: 'string',
            title: 'Factor'
        },
        peso: {
            type: 'integer',
            title: 'Peso'
        },
        valor: {
            type: 'integer',
            title: 'Valor'
        },
        contribucion: {
            type: 'integer',
            title: 'Contribucion'
        }
    },
    type: 'object',
    required: ['factor', 'peso', 'valor', 'contribucion'],
    title: 'FactorRiesgo'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const KYCStatusSchema = {
    type: 'string',
    enum: ['BORRADOR', 'PENDIENTE', 'EN_REVISION', 'APROBADO', 'RECHAZADO', 'DDR_INICIADO'],
    title: 'KYCStatus'
} as const;

export const ListaCoincidenciaSchema = {
    properties: {
        lista: {
            type: 'string',
            title: 'Lista'
        },
        nombre: {
            type: 'string',
            title: 'Nombre'
        },
        similitud: {
            type: 'integer',
            title: 'Similitud'
        }
    },
    type: 'object',
    required: ['lista', 'nombre', 'similitud'],
    title: 'ListaCoincidencia'
} as const;

export const ListasResultSchema = {
    properties: {
        ofac: {
            type: 'boolean',
            title: 'Ofac',
            default: false
        },
        onu: {
            type: 'boolean',
            title: 'Onu',
            default: false
        },
        ue: {
            type: 'boolean',
            title: 'Ue',
            default: false
        },
        coincidencias: {
            items: {
                '$ref': '#/components/schemas/ListaCoincidencia'
            },
            type: 'array',
            title: 'Coincidencias'
        }
    },
    type: 'object',
    title: 'ListasResult'
} as const;

export const LoginInputSchema = {
    properties: {
        correo: {
            type: 'string',
            title: 'Correo'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['correo', 'password'],
    title: 'LoginInput'
} as const;

export const LoginResponseSchema = {
    properties: {
        access_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        requires_2fa: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Requires 2Fa',
            default: false
        },
        temp_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Temp Token'
        },
        rol: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rol'
        },
        nombre: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nombre'
        }
    },
    type: 'object',
    title: 'LoginResponse',
    description: `Respuesta unificada de \`\`/auth/login\`\`.

Ramas:
* \`\`requires_2fa=False\`\` → \`\`access_token\`\` presente, \`\`temp_token=None\`\`.
* \`\`requires_2fa="verify"\`\` → \`\`temp_token\`\` para llamar a \`\`/2fa/verify\`\`.
* \`\`requires_2fa="setup"\`\` → \`\`temp_token\`\` para \`\`/2fa/setup/{start,confirm}\`\`.`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PersonaJuridicaCreateSchema = {
    properties: {
        razon_social: {
            type: 'string',
            maxLength: 200,
            title: 'Razon Social'
        },
        ruc: {
            type: 'string',
            maxLength: 50,
            title: 'Ruc'
        },
        tipo_sociedad: {
            type: 'string',
            maxLength: 30,
            title: 'Tipo Sociedad'
        },
        fecha_constitucion: {
            type: 'string',
            maxLength: 20,
            title: 'Fecha Constitucion'
        },
        pais_constitucion: {
            type: 'string',
            maxLength: 80,
            title: 'Pais Constitucion'
        },
        numero_registro_mercantil: {
            type: 'string',
            maxLength: 80,
            title: 'Numero Registro Mercantil'
        },
        nombre_representante: {
            type: 'string',
            maxLength: 150,
            title: 'Nombre Representante'
        },
        cedula_representante: {
            type: 'string',
            maxLength: 50,
            title: 'Cedula Representante'
        },
        cargo_representante: {
            type: 'string',
            maxLength: 80,
            title: 'Cargo Representante'
        },
        telefono_empresa: {
            type: 'string',
            maxLength: 30,
            title: 'Telefono Empresa'
        },
        email_empresa: {
            type: 'string',
            maxLength: 255,
            title: 'Email Empresa'
        },
        direccion_fiscal: {
            type: 'string',
            maxLength: 255,
            title: 'Direccion Fiscal'
        },
        ciudad: {
            type: 'string',
            maxLength: 100,
            title: 'Ciudad'
        },
        pais: {
            type: 'string',
            maxLength: 80,
            title: 'Pais'
        },
        actividad_economica: {
            type: 'string',
            maxLength: 200,
            title: 'Actividad Economica'
        },
        ingreso_anual_aproximado: {
            type: 'number',
            title: 'Ingreso Anual Aproximado',
            default: 0
        },
        cantidad_empleados: {
            type: 'integer',
            title: 'Cantidad Empleados',
            default: 0
        },
        tiene_accionistas_anonimos: {
            type: 'boolean',
            title: 'Tiene Accionistas Anonimos',
            default: false
        },
        opera_en_paises_alto_riesgo: {
            type: 'boolean',
            title: 'Opera En Paises Alto Riesgo',
            default: false
        }
    },
    type: 'object',
    required: ['razon_social', 'ruc', 'tipo_sociedad', 'fecha_constitucion', 'pais_constitucion', 'numero_registro_mercantil', 'nombre_representante', 'cedula_representante', 'cargo_representante', 'telefono_empresa', 'email_empresa', 'direccion_fiscal', 'ciudad', 'pais', 'actividad_economica'],
    title: 'PersonaJuridicaCreate'
} as const;

export const PersonaJuridicaPublicSchema = {
    properties: {
        razon_social: {
            type: 'string',
            maxLength: 200,
            title: 'Razon Social'
        },
        ruc: {
            type: 'string',
            maxLength: 50,
            title: 'Ruc'
        },
        tipo_sociedad: {
            type: 'string',
            maxLength: 30,
            title: 'Tipo Sociedad'
        },
        fecha_constitucion: {
            type: 'string',
            maxLength: 20,
            title: 'Fecha Constitucion'
        },
        pais_constitucion: {
            type: 'string',
            maxLength: 80,
            title: 'Pais Constitucion'
        },
        numero_registro_mercantil: {
            type: 'string',
            maxLength: 80,
            title: 'Numero Registro Mercantil'
        },
        nombre_representante: {
            type: 'string',
            maxLength: 150,
            title: 'Nombre Representante'
        },
        cedula_representante: {
            type: 'string',
            maxLength: 50,
            title: 'Cedula Representante'
        },
        cargo_representante: {
            type: 'string',
            maxLength: 80,
            title: 'Cargo Representante'
        },
        telefono_empresa: {
            type: 'string',
            maxLength: 30,
            title: 'Telefono Empresa'
        },
        email_empresa: {
            type: 'string',
            maxLength: 255,
            title: 'Email Empresa'
        },
        direccion_fiscal: {
            type: 'string',
            maxLength: 255,
            title: 'Direccion Fiscal'
        },
        ciudad: {
            type: 'string',
            maxLength: 100,
            title: 'Ciudad'
        },
        pais: {
            type: 'string',
            maxLength: 80,
            title: 'Pais'
        },
        actividad_economica: {
            type: 'string',
            maxLength: 200,
            title: 'Actividad Economica'
        },
        ingreso_anual_aproximado: {
            type: 'number',
            title: 'Ingreso Anual Aproximado',
            default: 0
        },
        cantidad_empleados: {
            type: 'integer',
            title: 'Cantidad Empleados',
            default: 0
        },
        tiene_accionistas_anonimos: {
            type: 'boolean',
            title: 'Tiene Accionistas Anonimos',
            default: false
        },
        opera_en_paises_alto_riesgo: {
            type: 'boolean',
            title: 'Opera En Paises Alto Riesgo',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['razon_social', 'ruc', 'tipo_sociedad', 'fecha_constitucion', 'pais_constitucion', 'numero_registro_mercantil', 'nombre_representante', 'cedula_representante', 'cargo_representante', 'telefono_empresa', 'email_empresa', 'direccion_fiscal', 'ciudad', 'pais', 'actividad_economica', 'id'],
    title: 'PersonaJuridicaPublic'
} as const;

export const PersonaNaturalCreateSchema = {
    properties: {
        tipo_documento: {
            type: 'string',
            maxLength: 30,
            title: 'Tipo Documento'
        },
        numero_documento: {
            type: 'string',
            maxLength: 50,
            title: 'Numero Documento'
        },
        fecha_expiracion_doc: {
            type: 'string',
            maxLength: 20,
            title: 'Fecha Expiracion Doc'
        },
        nacionalidad: {
            type: 'string',
            maxLength: 80,
            title: 'Nacionalidad'
        },
        pais_nacimiento: {
            type: 'string',
            maxLength: 80,
            title: 'Pais Nacimiento'
        },
        nombre: {
            type: 'string',
            maxLength: 100,
            title: 'Nombre'
        },
        apellido: {
            type: 'string',
            maxLength: 100,
            title: 'Apellido'
        },
        fecha_nacimiento: {
            type: 'string',
            maxLength: 20,
            title: 'Fecha Nacimiento'
        },
        genero: {
            type: 'string',
            maxLength: 20,
            title: 'Genero'
        },
        estado_civil: {
            type: 'string',
            maxLength: 20,
            title: 'Estado Civil'
        },
        telefono: {
            type: 'string',
            maxLength: 30,
            title: 'Telefono'
        },
        email: {
            type: 'string',
            maxLength: 255,
            title: 'Email'
        },
        direccion: {
            type: 'string',
            maxLength: 255,
            title: 'Direccion'
        },
        ciudad: {
            type: 'string',
            maxLength: 100,
            title: 'Ciudad'
        },
        pais: {
            type: 'string',
            maxLength: 80,
            title: 'Pais'
        },
        ocupacion: {
            type: 'string',
            maxLength: 120,
            title: 'Ocupacion'
        },
        empleador: {
            type: 'string',
            maxLength: 120,
            title: 'Empleador'
        },
        ingreso_mensual_aproximado: {
            type: 'number',
            title: 'Ingreso Mensual Aproximado',
            default: 0
        },
        fuente_ingresos: {
            type: 'string',
            maxLength: 60,
            title: 'Fuente Ingresos'
        },
        es_pep: {
            type: 'boolean',
            title: 'Es Pep',
            default: false
        },
        es_pep_familiar: {
            type: 'boolean',
            title: 'Es Pep Familiar',
            default: false
        },
        tiene_antecedentes: {
            type: 'boolean',
            title: 'Tiene Antecedentes',
            default: false
        }
    },
    type: 'object',
    required: ['tipo_documento', 'numero_documento', 'fecha_expiracion_doc', 'nacionalidad', 'pais_nacimiento', 'nombre', 'apellido', 'fecha_nacimiento', 'genero', 'estado_civil', 'telefono', 'email', 'direccion', 'ciudad', 'pais', 'ocupacion', 'empleador', 'fuente_ingresos'],
    title: 'PersonaNaturalCreate'
} as const;

export const PersonaNaturalPublicSchema = {
    properties: {
        tipo_documento: {
            type: 'string',
            maxLength: 30,
            title: 'Tipo Documento'
        },
        numero_documento: {
            type: 'string',
            maxLength: 50,
            title: 'Numero Documento'
        },
        fecha_expiracion_doc: {
            type: 'string',
            maxLength: 20,
            title: 'Fecha Expiracion Doc'
        },
        nacionalidad: {
            type: 'string',
            maxLength: 80,
            title: 'Nacionalidad'
        },
        pais_nacimiento: {
            type: 'string',
            maxLength: 80,
            title: 'Pais Nacimiento'
        },
        nombre: {
            type: 'string',
            maxLength: 100,
            title: 'Nombre'
        },
        apellido: {
            type: 'string',
            maxLength: 100,
            title: 'Apellido'
        },
        fecha_nacimiento: {
            type: 'string',
            maxLength: 20,
            title: 'Fecha Nacimiento'
        },
        genero: {
            type: 'string',
            maxLength: 20,
            title: 'Genero'
        },
        estado_civil: {
            type: 'string',
            maxLength: 20,
            title: 'Estado Civil'
        },
        telefono: {
            type: 'string',
            maxLength: 30,
            title: 'Telefono'
        },
        email: {
            type: 'string',
            maxLength: 255,
            title: 'Email'
        },
        direccion: {
            type: 'string',
            maxLength: 255,
            title: 'Direccion'
        },
        ciudad: {
            type: 'string',
            maxLength: 100,
            title: 'Ciudad'
        },
        pais: {
            type: 'string',
            maxLength: 80,
            title: 'Pais'
        },
        ocupacion: {
            type: 'string',
            maxLength: 120,
            title: 'Ocupacion'
        },
        empleador: {
            type: 'string',
            maxLength: 120,
            title: 'Empleador'
        },
        ingreso_mensual_aproximado: {
            type: 'number',
            title: 'Ingreso Mensual Aproximado',
            default: 0
        },
        fuente_ingresos: {
            type: 'string',
            maxLength: 60,
            title: 'Fuente Ingresos'
        },
        es_pep: {
            type: 'boolean',
            title: 'Es Pep',
            default: false
        },
        es_pep_familiar: {
            type: 'boolean',
            title: 'Es Pep Familiar',
            default: false
        },
        tiene_antecedentes: {
            type: 'boolean',
            title: 'Tiene Antecedentes',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['tipo_documento', 'numero_documento', 'fecha_expiracion_doc', 'nacionalidad', 'pais_nacimiento', 'nombre', 'apellido', 'fecha_nacimiento', 'genero', 'estado_civil', 'telefono', 'email', 'direccion', 'ciudad', 'pais', 'ocupacion', 'empleador', 'fuente_ingresos', 'id'],
    title: 'PersonaNaturalPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RechazoInputSchema = {
    properties: {
        observaciones: {
            type: 'string',
            maxLength: 1000,
            minLength: 20,
            title: 'Observaciones'
        }
    },
    type: 'object',
    required: ['observaciones'],
    title: 'RechazoInput'
} as const;

export const RiesgoResultSchema = {
    properties: {
        nivel: {
            '$ref': '#/components/schemas/RiskLevel'
        },
        puntaje: {
            type: 'integer',
            title: 'Puntaje'
        },
        factores: {
            items: {
                '$ref': '#/components/schemas/FactorRiesgo'
            },
            type: 'array',
            title: 'Factores'
        }
    },
    type: 'object',
    required: ['nivel', 'puntaje'],
    title: 'RiesgoResult'
} as const;

export const RiskLevelSchema = {
    type: 'string',
    enum: ['BAJO', 'MEDIO', 'ALTO', 'MUY_ALTO'],
    title: 'RiskLevel'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TwoFactorDisableInputSchema = {
    properties: {
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['password'],
    title: 'TwoFactorDisableInput'
} as const;

export const TwoFactorRegenerateInputSchema = {
    properties: {
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['password'],
    title: 'TwoFactorRegenerateInput'
} as const;

export const TwoFactorRegenerateResponseSchema = {
    properties: {
        backup_codes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Backup Codes'
        }
    },
    type: 'object',
    required: ['backup_codes'],
    title: 'TwoFactorRegenerateResponse'
} as const;

export const TwoFactorSetupConfirmInputSchema = {
    properties: {
        temp_token: {
            type: 'string',
            title: 'Temp Token'
        },
        code: {
            type: 'string',
            maxLength: 6,
            minLength: 6,
            title: 'Code'
        }
    },
    type: 'object',
    required: ['temp_token', 'code'],
    title: 'TwoFactorSetupConfirmInput'
} as const;

export const TwoFactorSetupConfirmResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        rol: {
            type: 'string',
            title: 'Rol'
        },
        nombre: {
            type: 'string',
            title: 'Nombre'
        },
        backup_codes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Backup Codes'
        }
    },
    type: 'object',
    required: ['access_token', 'rol', 'nombre', 'backup_codes'],
    title: 'TwoFactorSetupConfirmResponse',
    description: `Tras confirmar el setup, el usuario queda autenticado.

El frontend no necesita llamar a \`\`/2fa/verify\`\`: ya demostró posesión
del secret TOTP al verificar el código de confirmación.`
} as const;

export const TwoFactorSetupStartResponseSchema = {
    properties: {
        secret_base32: {
            type: 'string',
            title: 'Secret Base32'
        },
        otpauth_url: {
            type: 'string',
            title: 'Otpauth Url'
        },
        qr_png_base64: {
            type: 'string',
            title: 'Qr Png Base64'
        }
    },
    type: 'object',
    required: ['secret_base32', 'otpauth_url', 'qr_png_base64'],
    title: 'TwoFactorSetupStartResponse'
} as const;

export const TwoFactorStatusSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        required_by_role: {
            type: 'boolean',
            title: 'Required By Role'
        },
        backup_codes_remaining: {
            type: 'integer',
            title: 'Backup Codes Remaining'
        },
        confirmed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confirmed At'
        },
        disabled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disabled At'
        }
    },
    type: 'object',
    required: ['enabled', 'required_by_role', 'backup_codes_remaining'],
    title: 'TwoFactorStatus'
} as const;

export const TwoFactorVerifyInputSchema = {
    properties: {
        temp_token: {
            type: 'string',
            title: 'Temp Token'
        },
        code: {
            type: 'string',
            maxLength: 11,
            minLength: 6,
            title: 'Code'
        }
    },
    type: 'object',
    required: ['temp_token', 'code'],
    title: 'TwoFactorVerifyInput'
} as const;

export const TwoFactorVerifyResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        rol: {
            type: 'string',
            title: 'Rol'
        },
        nombre: {
            type: 'string',
            title: 'Nombre'
        }
    },
    type: 'object',
    required: ['access_token', 'rol', 'nombre'],
    title: 'TwoFactorVerifyResponse'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'OFICIAL_CUMPLIMIENTO'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'role', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['ADMIN', 'OFICIAL_CUMPLIMIENTO', 'ANALISTA_DDR', 'GERENTE_CUMPLIMIENTO', 'COMITE_CUMPLIMIENTO', 'AUDITOR'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserRole'
                },
                {
                    type: 'null'
                }
            ]
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;