// This file is auto-generated by @hey-api/openapi-ts

export type AprobacionInput = {
    observaciones?: (string | null);
};

export type AsignarAnalistaInput = {
    analista_id: string;
};

export type AuditoriaPublic = {
    id: string;
    usuario_id: (string | null);
    usuario_nombre?: (string | null);
    modulo: string;
    accion: string;
    entidad_tipo: (string | null);
    entidad_id: (string | null);
    descripcion: (string | null);
    ip_origen: (string | null);
    creado_en: string;
};

export type AuditoriasPublic = {
    data: Array<AuditoriaPublic>;
    count: number;
};

export type BeneficiarioFinalCreate = {
    nombre: string;
    apellido: string;
    cedula: string;
    nacionalidad: string;
    pais: string;
    fecha_nacimiento: string;
    porcentaje_participacion?: number;
    tipo_control?: string;
    es_pep?: boolean;
};

export type BeneficiarioFinalPublic = {
    nombre: string;
    apellido: string;
    cedula: string;
    nacionalidad: string;
    pais: string;
    fecha_nacimiento: string;
    porcentaje_participacion?: number;
    tipo_control?: string;
    es_pep?: boolean;
    id: string;
};

export type Body_casos_ddr_upload_documento_ddr = {
    tipo: DocumentoTipo;
    file: string;
};

export type Body_clientes_upload_documento = {
    tipo: DocumentoTipo;
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CasoDDRPublic = {
    id: string;
    expediente_id: string;
    nivel_riesgo: string;
    status: string;
    analista_id?: (string | null);
    aprobado_por_id?: (string | null);
    validado_por_id?: (string | null);
    observaciones_oficial?: (string | null);
    observaciones_rechazo?: (string | null);
    fecha_apertura?: (string | null);
    fecha_cierre?: (string | null);
    updated_at?: (string | null);
    cliente?: (ClienteResumen | null);
};

export type CasosDDRPublic = {
    data: Array<CasoDDRPublic>;
    count: number;
};

/**
 * Proyección mínima de un expediente KYC para embeber en otras
 * respuestas (casos DDR, dashboard, etc.) y evitar un round-trip extra.
 * Mantener sincronizado con la vista ``Cliente`` del frontend.
 */
export type ClienteResumen = {
    id: string;
    codigo: string;
    tipo_cliente: string;
    nombres: string;
    apellidos: string;
    tipo_identificacion: string;
    numero_identificacion: string;
    nivel_riesgo?: (string | null);
    estado: string;
    es_pep?: boolean;
};

export type ClientType = 'NATURAL' | 'JURIDICA';

export type CuestionarioEBRPublic = {
    id: string;
    caso_ddr_id: string;
    origen_fondos?: (string | null);
    proposito_relacion?: (string | null);
    patrimonio_estimado?: (string | null);
    pais_origen_patrimonio?: (string | null);
    tiene_estructura_societaria?: (boolean | null);
    familiar_pep?: (boolean | null);
    completado?: boolean;
    completado_por?: (string | null);
    completado_en?: (string | null);
};

export type CuestionarioUpdate = {
    origen_fondos?: (string | null);
    proposito_relacion?: (string | null);
    patrimonio_estimado?: (string | null);
    pais_origen_patrimonio?: (string | null);
    tiene_estructura_societaria?: (boolean | null);
    familiar_pep?: (boolean | null);
};

export type DevolucionInput = {
    observaciones: string;
};

export type DocumentoEstado = 'PENDIENTE' | 'VALIDADO' | 'RECHAZADO';

export type DocumentoKYCPublic = {
    id: string;
    expediente_id: string;
    caso_ddr_id?: (string | null);
    tipo: DocumentoTipo;
    nombre: string;
    tamanio: number;
    mime_type: string;
    estado: DocumentoEstado;
    hash_sha256?: (string | null);
    fecha_carga?: (string | null);
};

export type DocumentosDDRPublic = {
    data: Array<DocumentoKYCPublic>;
    count: number;
};

export type DocumentoTipo = 'CEDULA_FRONTAL' | 'CEDULA_POSTERIOR' | 'PASAPORTE' | 'RUC' | 'REGISTRO_MERCANTIL' | 'ESTADOS_FINANCIEROS' | 'DECLARACION_RENTA' | 'ESCRITURA_CONSTITUCION' | 'PODER_REPRESENTANTE' | 'DECLARACION_FONDOS' | 'REFERENCIA_BANCARIA' | 'COMPROBANTE_DOMICILIO' | 'OTRO';

/**
 * Flujo DDR con segregación de funciones (cuatro ojos):
 *
 * ABIERTO → el Oficial asigna un analista (distinto al que registró)
 * EN_REVISION → el analista investiga (EBR + documentos)
 * EN_REVISION_OFICIAL → el Oficial valida el trabajo del analista
 * EN_APROBACION → Gerente (ALTO) o Comité (MUY_ALTO) decide
 * APROBADO / RECHAZADO → cierre
 */
export type EstadoCasoDDR = 'ABIERTO' | 'EN_REVISION' | 'EN_REVISION_OFICIAL' | 'EN_APROBACION' | 'APROBADO' | 'RECHAZADO';

export type ExpedienteKYCCreate = {
    tipo_cliente: ClientType;
    persona_natural?: (PersonaNaturalCreate | null);
    persona_juridica?: (PersonaJuridicaCreate | null);
    beneficiarios_final?: Array<BeneficiarioFinalCreate>;
    enviar_a_revision?: boolean;
};

export type ExpedienteKYCPublic = {
    id: string;
    codigo: string;
    tipo_cliente: ClientType;
    status: KYCStatus;
    nivel_riesgo?: (RiskLevel | null);
    puntaje_riesgo?: (number | null);
    nivel_riesgo_override?: (RiskLevel | null);
    justificacion_override?: (string | null);
    comentario_rechazo?: (string | null);
    analista_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    persona_natural?: (PersonaNaturalPublic | null);
    persona_juridica?: (PersonaJuridicaPublic | null);
    beneficiarios_final?: Array<BeneficiarioFinalPublic>;
    documentos?: Array<DocumentoKYCPublic>;
};

export type ExpedienteKYCUpdate = {
    status?: (KYCStatus | null);
    comentario_rechazo?: (string | null);
};

export type ExpedientesKYCPublic = {
    data: Array<ExpedienteKYCPublic>;
    count: number;
};

export type FactorRiesgo = {
    factor: string;
    peso: number;
    valor: number;
    contribucion: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type KYCStatus = 'BORRADOR' | 'PENDIENTE' | 'EN_REVISION' | 'APROBADO' | 'RECHAZADO' | 'DDR_INICIADO';

export type ListaCoincidencia = {
    lista: string;
    nombre: string;
    similitud: number;
};

export type ListasResult = {
    ofac?: boolean;
    onu?: boolean;
    ue?: boolean;
    coincidencias?: Array<ListaCoincidencia>;
};

export type LoginInput = {
    correo: string;
    password: string;
};

/**
 * Respuesta unificada de ``/auth/login``.
 *
 * Ramas:
 * * ``requires_2fa=False`` → ``access_token`` presente, ``temp_token=None``.
 * * ``requires_2fa="verify"`` → ``temp_token`` para llamar a ``/2fa/verify``.
 * * ``requires_2fa="setup"`` → ``temp_token`` para ``/2fa/setup/{start,confirm}``.
 */
export type LoginResponse = {
    access_token?: (string | null);
    token_type?: string;
    requires_2fa?: (boolean | string);
    temp_token?: (string | null);
    rol?: (string | null);
    nombre?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type ParametroRiesgoPublic = {
    id: string;
    factor: string;
    descripcion: string;
    peso: number;
    activo: boolean;
};

export type ParametroRiesgoUpdate = {
    peso: number;
    activo?: (boolean | null);
};

export type PersonaJuridicaCreate = {
    razon_social: string;
    ruc: string;
    tipo_sociedad: string;
    fecha_constitucion: string;
    pais_constitucion: string;
    numero_registro_mercantil: string;
    nombre_representante: string;
    cedula_representante: string;
    cargo_representante: string;
    telefono_empresa: string;
    email_empresa: string;
    direccion_fiscal: string;
    ciudad: string;
    pais: string;
    actividad_economica: string;
    ingreso_anual_aproximado?: number;
    cantidad_empleados?: number;
    tiene_accionistas_anonimos?: boolean;
    opera_en_paises_alto_riesgo?: boolean;
};

export type PersonaJuridicaPublic = {
    razon_social: string;
    ruc: string;
    tipo_sociedad: string;
    fecha_constitucion: string;
    pais_constitucion: string;
    numero_registro_mercantil: string;
    nombre_representante: string;
    cedula_representante: string;
    cargo_representante: string;
    telefono_empresa: string;
    email_empresa: string;
    direccion_fiscal: string;
    ciudad: string;
    pais: string;
    actividad_economica: string;
    ingreso_anual_aproximado?: number;
    cantidad_empleados?: number;
    tiene_accionistas_anonimos?: boolean;
    opera_en_paises_alto_riesgo?: boolean;
    id: string;
};

export type PersonaNaturalCreate = {
    tipo_documento: string;
    numero_documento: string;
    fecha_expiracion_doc: string;
    nacionalidad: string;
    pais_nacimiento: string;
    nombre: string;
    apellido: string;
    fecha_nacimiento: string;
    genero: string;
    estado_civil: string;
    telefono: string;
    email: string;
    direccion: string;
    ciudad: string;
    pais: string;
    ocupacion: string;
    empleador: string;
    ingreso_mensual_aproximado?: number;
    fuente_ingresos: string;
    es_pep?: boolean;
    es_pep_familiar?: boolean;
    tiene_antecedentes?: boolean;
};

export type PersonaNaturalPublic = {
    tipo_documento: string;
    numero_documento: string;
    fecha_expiracion_doc: string;
    nacionalidad: string;
    pais_nacimiento: string;
    nombre: string;
    apellido: string;
    fecha_nacimiento: string;
    genero: string;
    estado_civil: string;
    telefono: string;
    email: string;
    direccion: string;
    ciudad: string;
    pais: string;
    ocupacion: string;
    empleador: string;
    ingreso_mensual_aproximado?: number;
    fuente_ingresos: string;
    es_pep?: boolean;
    es_pep_familiar?: boolean;
    tiene_antecedentes?: boolean;
    id: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RechazoInput = {
    observaciones: string;
};

export type RiesgoOverrideInput = {
    nivel_riesgo_override: RiskLevel;
    justificacion_override: string;
};

export type RiesgoResult = {
    nivel: RiskLevel;
    puntaje: number;
    factores?: Array<FactorRiesgo>;
};

export type RiskLevel = 'BAJO' | 'MEDIO' | 'ALTO' | 'MUY_ALTO';

export type ScreeningResultadoPublic = {
    id: string;
    expediente_id: string;
    lista: string;
    nombre_entrada: string;
    similitud: number;
    es_falso_positivo: boolean;
    revisado_por_id: (string | null);
    revisado_en: (string | null);
    creado_en: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TwoFactorDisableInput = {
    password: string;
};

export type TwoFactorRegenerateInput = {
    password: string;
};

export type TwoFactorRegenerateResponse = {
    backup_codes: Array<(string)>;
};

export type TwoFactorSetupConfirmInput = {
    temp_token: string;
    code: string;
};

/**
 * Tras confirmar el setup, el usuario queda autenticado.
 *
 * El frontend no necesita llamar a ``/2fa/verify``: ya demostró posesión
 * del secret TOTP al verificar el código de confirmación.
 */
export type TwoFactorSetupConfirmResponse = {
    access_token: string;
    token_type?: string;
    rol: string;
    nombre: string;
    backup_codes: Array<(string)>;
};

export type TwoFactorSetupStartResponse = {
    secret_base32: string;
    otpauth_url: string;
    qr_png_base64: string;
};

export type TwoFactorStatus = {
    enabled: boolean;
    required_by_role: boolean;
    backup_codes_remaining: number;
    confirmed_at?: (string | null);
    disabled_at?: (string | null);
};

export type TwoFactorVerifyInput = {
    temp_token: string;
    code: string;
};

export type TwoFactorVerifyResponse = {
    access_token: string;
    token_type?: string;
    rol: string;
    nombre: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role: UserRole;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'ADMIN' | 'OFICIAL_CUMPLIMIENTO' | 'ANALISTA_DDR' | 'GERENTE_CUMPLIMIENTO' | 'COMITE_CUMPLIMIENTO' | 'AUDITOR';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: (UserRole | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuditoriaReadAuditoriaData = {
    desde?: (string | null);
    hasta?: (string | null);
    limit?: number;
    modulo?: (string | null);
    skip?: number;
    usuarioId?: (string | null);
};

export type AuditoriaReadAuditoriaResponse = (AuditoriasPublic);

export type AuthLoginData = {
    requestBody: LoginInput;
};

export type AuthLoginResponse = (LoginResponse);

export type AuthLogoutResponse = (Message);

export type AuthExtendSessionResponse = (Token);

export type AuthTwofaSetupStartData = {
    requestBody: TwoFactorVerifyInput;
};

export type AuthTwofaSetupStartResponse = (TwoFactorSetupStartResponse);

export type AuthTwofaSetupConfirmData = {
    requestBody: TwoFactorSetupConfirmInput;
};

export type AuthTwofaSetupConfirmResponse = (TwoFactorSetupConfirmResponse);

export type AuthTwofaVerifyData = {
    requestBody: TwoFactorVerifyInput;
};

export type AuthTwofaVerifyResponse = (TwoFactorVerifyResponse);

export type AuthTwofaStatusResponse = (TwoFactorStatus);

export type AuthTwofaDisableData = {
    requestBody: TwoFactorDisableInput;
};

export type AuthTwofaDisableResponse = (Message);

export type AuthTwofaRegenerateBackupCodesData = {
    requestBody: TwoFactorRegenerateInput;
};

export type AuthTwofaRegenerateBackupCodesResponse = (TwoFactorRegenerateResponse);

export type CasosDdrReadCasosDdrData = {
    limit?: number;
    nivelRiesgo?: (string | null);
    skip?: number;
    status?: (EstadoCasoDDR | null);
};

export type CasosDdrReadCasosDdrResponse = (CasosDDRPublic);

export type CasosDdrEstadisticasCasosDdrResponse = (unknown);

export type CasosDdrReadCasoDdrData = {
    id: string;
};

export type CasosDdrReadCasoDdrResponse = (CasoDDRPublic);

export type CasosDdrReadExpedienteDelCasoData = {
    id: string;
};

export type CasosDdrReadExpedienteDelCasoResponse = (ExpedienteKYCPublic);

export type CasosDdrAsignarAnalistaData = {
    id: string;
    requestBody: AsignarAnalistaInput;
};

export type CasosDdrAsignarAnalistaResponse = (CasoDDRPublic);

export type CasosDdrEnviarAprobacionData = {
    id: string;
};

export type CasosDdrEnviarAprobacionResponse = (CasoDDRPublic);

export type CasosDdrValidarCasoData = {
    id: string;
};

export type CasosDdrValidarCasoResponse = (CasoDDRPublic);

export type CasosDdrDevolverCasoData = {
    id: string;
    requestBody: DevolucionInput;
};

export type CasosDdrDevolverCasoResponse = (CasoDDRPublic);

export type CasosDdrReabrirCasoData = {
    id: string;
};

export type CasosDdrReabrirCasoResponse = (CasoDDRPublic);

export type CasosDdrDevolverAOficialData = {
    id: string;
    requestBody: DevolucionInput;
};

export type CasosDdrDevolverAOficialResponse = (CasoDDRPublic);

export type CasosDdrAprobarCasoData = {
    id: string;
    requestBody?: (AprobacionInput | null);
};

export type CasosDdrAprobarCasoResponse = (CasoDDRPublic);

export type CasosDdrRechazarCasoData = {
    id: string;
    requestBody: RechazoInput;
};

export type CasosDdrRechazarCasoResponse = (CasoDDRPublic);

export type CasosDdrGetCuestionarioData = {
    id: string;
};

export type CasosDdrGetCuestionarioResponse = (CuestionarioEBRPublic);

export type CasosDdrUpdateCuestionarioData = {
    id: string;
    requestBody: CuestionarioUpdate;
};

export type CasosDdrUpdateCuestionarioResponse = (CuestionarioEBRPublic);

export type CasosDdrUploadDocumentoDdrData = {
    formData: Body_casos_ddr_upload_documento_ddr;
    id: string;
};

export type CasosDdrUploadDocumentoDdrResponse = (DocumentoKYCPublic);

export type CasosDdrListDocumentosDdrData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type CasosDdrListDocumentosDdrResponse = (DocumentosDDRPublic);

export type ClientesCreateClienteData = {
    requestBody: ExpedienteKYCCreate;
};

export type ClientesCreateClienteResponse = (ExpedienteKYCPublic);

export type ClientesReadClientesData = {
    limit?: number;
    riesgo?: (RiskLevel | null);
    search?: (string | null);
    skip?: number;
    status?: (KYCStatus | null);
    tipo?: (ClientType | null);
};

export type ClientesReadClientesResponse = (ExpedientesKYCPublic);

export type ClientesEstadisticasClientesResponse = (unknown);

export type ClientesReadClienteData = {
    id: string;
};

export type ClientesReadClienteResponse = (ExpedienteKYCPublic);

export type ClientesUpdateClienteData = {
    id: string;
    requestBody: ExpedienteKYCUpdate;
};

export type ClientesUpdateClienteResponse = (ExpedienteKYCPublic);

export type ClientesUploadDocumentoData = {
    formData: Body_clientes_upload_documento;
    id: string;
};

export type ClientesUploadDocumentoResponse = (DocumentoKYCPublic);

export type ClientesDeleteDocumentoData = {
    docId: string;
    id: string;
};

export type ClientesDeleteDocumentoResponse = (Message);

export type ClientesDescargarDocumentoData = {
    disposition?: string;
    docId: string;
    id: string;
};

export type ClientesDescargarDocumentoResponse = (unknown);

export type ClientesEvaluarRiesgoData = {
    id: string;
};

export type ClientesEvaluarRiesgoResponse = (RiesgoResult);

export type ClientesVerificarListasData = {
    id: string;
};

export type ClientesVerificarListasResponse = (ListasResult);

export type ClientesListarScreeningData = {
    id: string;
};

export type ClientesListarScreeningResponse = (Array<ScreeningResultadoPublic>);

export type ClientesMarcarFalsoPositivoData = {
    id: string;
    resultadoId: string;
};

export type ClientesMarcarFalsoPositivoResponse = (ScreeningResultadoPublic);

export type ClientesFactoresRiesgoData = {
    id: string;
};

export type ClientesFactoresRiesgoResponse = (RiesgoResult);

export type ClientesOverrideRiesgoData = {
    id: string;
    requestBody: RiesgoOverrideInput;
};

export type ClientesOverrideRiesgoResponse = (ExpedienteKYCPublic);

export type DashboardGetDashboardResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ParametrosListarParametrosResponse = (Array<ParametroRiesgoPublic>);

export type ParametrosActualizarParametroData = {
    id: string;
    requestBody: ParametroRiesgoUpdate;
};

export type ParametrosActualizarParametroResponse = (ParametroRiesgoPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);