"""add caso_ddr cuestionario_ebr y hash_doc

Revision ID: 69feb88c7960
Revises: 804feedfad7a
Create Date: 2026-06-15 02:00:56.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '69feb88c7960'
down_revision = '804feedfad7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso_ddr',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expediente_id', sa.Uuid(), nullable=False),
    sa.Column('nivel_riesgo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('analista_id', sa.Uuid(), nullable=True),
    sa.Column('aprobado_por_id', sa.Uuid(), nullable=True),
    sa.Column('observaciones_rechazo', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analista_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientekyc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expediente_id')
    )
    op.create_table('cuestionario_ebr',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caso_ddr_id', sa.Uuid(), nullable=False),
    sa.Column('origen_fondos', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('proposito_relacion', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('patrimonio_estimado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('pais_origen_patrimonio', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('tiene_estructura_societaria', sa.Boolean(), nullable=True),
    sa.Column('familiar_pep', sa.Boolean(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('completado_por', sa.Uuid(), nullable=True),
    sa.Column('completado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['caso_ddr_id'], ['caso_ddr.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completado_por'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caso_ddr_id')
    )
    op.add_column('documentokyc', sa.Column('caso_ddr_id', sa.Uuid(), nullable=True))
    op.add_column('documentokyc', sa.Column('hash_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_foreign_key(None, 'documentokyc', 'caso_ddr', ['caso_ddr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentokyc', type_='foreignkey')
    op.drop_column('documentokyc', 'hash_sha256')
    op.drop_column('documentokyc', 'caso_ddr_id')
    op.drop_table('cuestionario_ebr')
    op.drop_table('caso_ddr')
    # ### end Alembic commands ###
