"""add kyc tables

Revision ID: 804feedfad7a
Revises: b7e1c9a2d4f8
Create Date: 2026-06-09 02:38:11.782027

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '804feedfad7a'
down_revision = 'b7e1c9a2d4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expedientekyc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tipo_cliente', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nivel_riesgo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('puntaje_riesgo', sa.Integer(), nullable=True),
    sa.Column('comentario_rechazo', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('analista_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analista_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expedientekyc_codigo'), 'expedientekyc', ['codigo'], unique=True)
    op.create_table('beneficiariofinal',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('cedula', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nacionalidad', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('fecha_nacimiento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('porcentaje_participacion', sa.Float(), nullable=False),
    sa.Column('es_pep', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expediente_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientekyc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentokyc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expediente_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tamanio', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ruta_archivo', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientekyc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personajuridica',
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('ruc', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tipo_sociedad', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('fecha_constitucion', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('pais_constitucion', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('numero_registro_mercantil', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('nombre_representante', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('cedula_representante', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('cargo_representante', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('telefono_empresa', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('email_empresa', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('direccion_fiscal', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('actividad_economica', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('ingreso_anual_aproximado', sa.Float(), nullable=False),
    sa.Column('cantidad_empleados', sa.Integer(), nullable=False),
    sa.Column('tiene_accionistas_anonimos', sa.Boolean(), nullable=False),
    sa.Column('opera_en_paises_alto_riesgo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expediente_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientekyc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personanatural',
    sa.Column('tipo_documento', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('numero_documento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_expiracion_doc', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nacionalidad', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('pais_nacimiento', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('genero', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('estado_civil', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('ocupacion', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('empleador', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('ingreso_mensual_aproximado', sa.Float(), nullable=False),
    sa.Column('fuente_ingresos', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('es_pep', sa.Boolean(), nullable=False),
    sa.Column('es_pep_familiar', sa.Boolean(), nullable=False),
    sa.Column('tiene_antecedentes', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expediente_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientekyc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personanatural')
    op.drop_table('personajuridica')
    op.drop_table('documentokyc')
    op.drop_table('beneficiariofinal')
    op.drop_index(op.f('ix_expedientekyc_codigo'), table_name='expedientekyc')
    op.drop_table('expedientekyc')
    # ### end Alembic commands ###
