/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountLockedRouteImport } from './routes/account-locked'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsuariosRouteImport } from './routes/_layout/usuarios'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutKycIndexRouteImport } from './routes/_layout/kyc/index'
import { Route as LayoutKycNuevoRouteImport } from './routes/_layout/kyc/nuevo'
import { Route as LayoutClientesIndexRouteImport } from './routes/_layout/clientes/index'
import { Route as LayoutClientesIdRouteImport } from './routes/_layout/clientes/$id'
import { Route as LayoutCasosDdrIndexRouteImport } from './routes/_layout/casos-ddr/index'
import { Route as LayoutCasosDdrIdRouteImport } from './routes/_layout/casos-ddr/$id'
import { Route as LayoutCasosDdrIdEvaluacionRouteImport } from './routes/_layout/casos-ddr/$id.evaluacion'

const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLockedRoute = AccountLockedRouteImport.update({
  id: '/account-locked',
  path: '/account-locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsuariosRoute = LayoutUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKycIndexRoute = LayoutKycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKycNuevoRoute = LayoutKycNuevoRouteImport.update({
  id: '/kyc/nuevo',
  path: '/kyc/nuevo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientesIndexRoute = LayoutClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientesIdRoute = LayoutClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasosDdrIndexRoute = LayoutCasosDdrIndexRouteImport.update({
  id: '/casos-ddr/',
  path: '/casos-ddr/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasosDdrIdRoute = LayoutCasosDdrIdRouteImport.update({
  id: '/casos-ddr/$id',
  path: '/casos-ddr/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasosDdrIdEvaluacionRoute =
  LayoutCasosDdrIdEvaluacionRouteImport.update({
    id: '/casos-ddr/$id/evaluacion',
    path: '/casos-ddr/$id/evaluacion',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/account-locked': typeof AccountLockedRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/usuarios': typeof LayoutUsuariosRoute
  '/kyc/nuevo': typeof LayoutKycNuevoRoute
  '/kyc/': typeof LayoutKycIndexRoute
  '/clientes/$id': typeof LayoutClientesIdRoute
  '/casos-ddr/$id': typeof LayoutCasosDdrIdRoute
  '/casos-ddr/$id/evaluacion': typeof LayoutCasosDdrIdEvaluacionRoute
  '/clientes/': typeof LayoutClientesIndexRoute
  '/casos-ddr/': typeof LayoutCasosDdrIndexRoute
}
export interface FileRoutesByTo {
  '/account-locked': typeof AccountLockedRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/usuarios': typeof LayoutUsuariosRoute
  '/': typeof LayoutIndexRoute
  '/kyc/nuevo': typeof LayoutKycNuevoRoute
  '/kyc': typeof LayoutKycIndexRoute
  '/clientes/$id': typeof LayoutClientesIdRoute
  '/casos-ddr/$id': typeof LayoutCasosDdrIdRoute
  '/casos-ddr/$id/evaluacion': typeof LayoutCasosDdrIdEvaluacionRoute
  '/clientes': typeof LayoutClientesIndexRoute
  '/casos-ddr': typeof LayoutCasosDdrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/account-locked': typeof AccountLockedRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/usuarios': typeof LayoutUsuariosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/kyc/nuevo': typeof LayoutKycNuevoRoute
  '/_layout/kyc/': typeof LayoutKycIndexRoute
  '/_layout/clientes/$id': typeof LayoutClientesIdRoute
  '/_layout/casos-ddr/$id': typeof LayoutCasosDdrIdRoute
  '/_layout/casos-ddr/$id/evaluacion': typeof LayoutCasosDdrIdEvaluacionRoute
  '/_layout/clientes/': typeof LayoutClientesIndexRoute
  '/_layout/casos-ddr/': typeof LayoutCasosDdrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-locked'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/admin'
    | '/items'
    | '/settings'
    | '/usuarios'
    | '/kyc/nuevo'
    | '/kyc/'
    | '/clientes/$id'
    | '/casos-ddr/$id'
    | '/casos-ddr/$id/evaluacion'
    | '/clientes/'
    | '/casos-ddr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account-locked'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/admin'
    | '/items'
    | '/settings'
    | '/usuarios'
    | '/'
    | '/kyc/nuevo'
    | '/kyc'
    | '/clientes/$id'
    | '/casos-ddr/$id'
    | '/casos-ddr/$id/evaluacion'
    | '/clientes'
    | '/casos-ddr'
  id:
    | '__root__'
    | '/_layout'
    | '/account-locked'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/usuarios'
    | '/_layout/'
    | '/_layout/kyc/nuevo'
    | '/_layout/kyc/'
    | '/_layout/clientes/$id'
    | '/_layout/casos-ddr/$id'
    | '/_layout/casos-ddr/$id/evaluacion'
    | '/_layout/clientes/'
    | '/_layout/casos-ddr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AccountLockedRoute: typeof AccountLockedRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TwoFactorRoute: typeof TwoFactorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-locked': {
      id: '/account-locked'
      path: '/account-locked'
      fullPath: '/account-locked'
      preLoaderRoute: typeof AccountLockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/usuarios': {
      id: '/_layout/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof LayoutUsuariosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kyc/': {
      id: '/_layout/kyc/'
      path: '/kyc'
      fullPath: '/kyc/'
      preLoaderRoute: typeof LayoutKycIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kyc/nuevo': {
      id: '/_layout/kyc/nuevo'
      path: '/kyc/nuevo'
      fullPath: '/kyc/nuevo'
      preLoaderRoute: typeof LayoutKycNuevoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clientes/': {
      id: '/_layout/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof LayoutClientesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clientes/$id': {
      id: '/_layout/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof LayoutClientesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/casos-ddr/': {
      id: '/_layout/casos-ddr/'
      path: '/casos-ddr'
      fullPath: '/casos-ddr/'
      preLoaderRoute: typeof LayoutCasosDdrIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/casos-ddr/$id': {
      id: '/_layout/casos-ddr/$id'
      path: '/casos-ddr/$id'
      fullPath: '/casos-ddr/$id'
      preLoaderRoute: typeof LayoutCasosDdrIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/casos-ddr/$id/evaluacion': {
      id: '/_layout/casos-ddr/$id/evaluacion'
      path: '/casos-ddr/$id/evaluacion'
      fullPath: '/casos-ddr/$id/evaluacion'
      preLoaderRoute: typeof LayoutCasosDdrIdEvaluacionRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUsuariosRoute: typeof LayoutUsuariosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutKycNuevoRoute: typeof LayoutKycNuevoRoute
  LayoutKycIndexRoute: typeof LayoutKycIndexRoute
  LayoutClientesIndexRoute: typeof LayoutClientesIndexRoute
  LayoutClientesIdRoute: typeof LayoutClientesIdRoute
  LayoutCasosDdrIndexRoute: typeof LayoutCasosDdrIndexRoute
  LayoutCasosDdrIdRoute: typeof LayoutCasosDdrIdRoute
  LayoutCasosDdrIdEvaluacionRoute: typeof LayoutCasosDdrIdEvaluacionRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUsuariosRoute: LayoutUsuariosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutKycNuevoRoute: LayoutKycNuevoRoute,
  LayoutKycIndexRoute: LayoutKycIndexRoute,
  LayoutClientesIndexRoute: LayoutClientesIndexRoute,
  LayoutClientesIdRoute: LayoutClientesIdRoute,
  LayoutCasosDdrIndexRoute: LayoutCasosDdrIndexRoute,
  LayoutCasosDdrIdRoute: LayoutCasosDdrIdRoute,
  LayoutCasosDdrIdEvaluacionRoute: LayoutCasosDdrIdEvaluacionRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AccountLockedRoute: AccountLockedRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TwoFactorRoute: TwoFactorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
