/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountLockedRouteImport } from './routes/account-locked'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as TwoFactorSetupRouteImport } from './routes/two-factor.setup'
import { Route as LayoutUsuariosRouteImport } from './routes/_layout/usuarios'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutKycIndexRouteImport } from './routes/_layout/kyc/index'
import { Route as LayoutClientesIndexRouteImport } from './routes/_layout/clientes/index'
import { Route as LayoutCasosDdrIndexRouteImport } from './routes/_layout/casos-ddr/index'
import { Route as LayoutKycNuevoRouteImport } from './routes/_layout/kyc/nuevo'
import { Route as LayoutClientesIdRouteImport } from './routes/_layout/clientes/$id'
import { Route as LayoutCasosDdrIdRouteImport } from './routes/_layout/casos-ddr/$id'
import { Route as LayoutCasosDdrIdEvaluacionRouteImport } from './routes/_layout/casos-ddr/$id.evaluacion'

const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLockedRoute = AccountLockedRouteImport.update({
  id: '/account-locked',
  path: '/account-locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const TwoFactorSetupRoute = TwoFactorSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => TwoFactorRoute,
} as any)
const LayoutUsuariosRoute = LayoutUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKycIndexRoute = LayoutKycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientesIndexRoute = LayoutClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasosDdrIndexRoute = LayoutCasosDdrIndexRouteImport.update({
  id: '/casos-ddr/',
  path: '/casos-ddr/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKycNuevoRoute = LayoutKycNuevoRouteImport.update({
  id: '/kyc/nuevo',
  path: '/kyc/nuevo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientesIdRoute = LayoutClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasosDdrIdRoute = LayoutCasosDdrIdRouteImport.update({
  id: '/casos-ddr/$id',
  path: '/casos-ddr/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasosDdrIdEvaluacionRoute =
  LayoutCasosDdrIdEvaluacionRouteImport.update({
    id: '/evaluacion',
    path: '/evaluacion',
    getParentRoute: () => LayoutCasosDdrIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/account-locked': typeof AccountLockedRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/two-factor': typeof TwoFactorRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/usuarios': typeof LayoutUsuariosRoute
  '/two-factor/setup': typeof TwoFactorSetupRoute
  '/casos-ddr/$id': typeof LayoutCasosDdrIdRouteWithChildren
  '/clientes/$id': typeof LayoutClientesIdRoute
  '/kyc/nuevo': typeof LayoutKycNuevoRoute
  '/casos-ddr/': typeof LayoutCasosDdrIndexRoute
  '/clientes/': typeof LayoutClientesIndexRoute
  '/kyc/': typeof LayoutKycIndexRoute
  '/casos-ddr/$id/evaluacion': typeof LayoutCasosDdrIdEvaluacionRoute
}
export interface FileRoutesByTo {
  '/account-locked': typeof AccountLockedRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/two-factor': typeof TwoFactorRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/usuarios': typeof LayoutUsuariosRoute
  '/two-factor/setup': typeof TwoFactorSetupRoute
  '/': typeof LayoutIndexRoute
  '/casos-ddr/$id': typeof LayoutCasosDdrIdRouteWithChildren
  '/clientes/$id': typeof LayoutClientesIdRoute
  '/kyc/nuevo': typeof LayoutKycNuevoRoute
  '/casos-ddr': typeof LayoutCasosDdrIndexRoute
  '/clientes': typeof LayoutClientesIndexRoute
  '/kyc': typeof LayoutKycIndexRoute
  '/casos-ddr/$id/evaluacion': typeof LayoutCasosDdrIdEvaluacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/account-locked': typeof AccountLockedRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/two-factor': typeof TwoFactorRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/usuarios': typeof LayoutUsuariosRoute
  '/two-factor/setup': typeof TwoFactorSetupRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/casos-ddr/$id': typeof LayoutCasosDdrIdRouteWithChildren
  '/_layout/clientes/$id': typeof LayoutClientesIdRoute
  '/_layout/kyc/nuevo': typeof LayoutKycNuevoRoute
  '/_layout/casos-ddr/': typeof LayoutCasosDdrIndexRoute
  '/_layout/clientes/': typeof LayoutClientesIndexRoute
  '/_layout/kyc/': typeof LayoutKycIndexRoute
  '/_layout/casos-ddr/$id/evaluacion': typeof LayoutCasosDdrIdEvaluacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-locked'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/two-factor'
    | '/admin'
    | '/settings'
    | '/usuarios'
    | '/two-factor/setup'
    | '/casos-ddr/$id'
    | '/clientes/$id'
    | '/kyc/nuevo'
    | '/casos-ddr/'
    | '/clientes/'
    | '/kyc/'
    | '/casos-ddr/$id/evaluacion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account-locked'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/two-factor'
    | '/admin'
    | '/settings'
    | '/usuarios'
    | '/two-factor/setup'
    | '/'
    | '/casos-ddr/$id'
    | '/clientes/$id'
    | '/kyc/nuevo'
    | '/casos-ddr'
    | '/clientes'
    | '/kyc'
    | '/casos-ddr/$id/evaluacion'
  id:
    | '__root__'
    | '/_layout'
    | '/account-locked'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/two-factor'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/usuarios'
    | '/two-factor/setup'
    | '/_layout/'
    | '/_layout/casos-ddr/$id'
    | '/_layout/clientes/$id'
    | '/_layout/kyc/nuevo'
    | '/_layout/casos-ddr/'
    | '/_layout/clientes/'
    | '/_layout/kyc/'
    | '/_layout/casos-ddr/$id/evaluacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AccountLockedRoute: typeof AccountLockedRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TwoFactorRoute: typeof TwoFactorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-locked': {
      id: '/account-locked'
      path: '/account-locked'
      fullPath: '/account-locked'
      preLoaderRoute: typeof AccountLockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/two-factor/setup': {
      id: '/two-factor/setup'
      path: '/setup'
      fullPath: '/two-factor/setup'
      preLoaderRoute: typeof TwoFactorSetupRouteImport
      parentRoute: typeof TwoFactorRoute
    }
    '/_layout/usuarios': {
      id: '/_layout/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof LayoutUsuariosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kyc/': {
      id: '/_layout/kyc/'
      path: '/kyc'
      fullPath: '/kyc/'
      preLoaderRoute: typeof LayoutKycIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clientes/': {
      id: '/_layout/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof LayoutClientesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/casos-ddr/': {
      id: '/_layout/casos-ddr/'
      path: '/casos-ddr'
      fullPath: '/casos-ddr/'
      preLoaderRoute: typeof LayoutCasosDdrIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kyc/nuevo': {
      id: '/_layout/kyc/nuevo'
      path: '/kyc/nuevo'
      fullPath: '/kyc/nuevo'
      preLoaderRoute: typeof LayoutKycNuevoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clientes/$id': {
      id: '/_layout/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof LayoutClientesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/casos-ddr/$id': {
      id: '/_layout/casos-ddr/$id'
      path: '/casos-ddr/$id'
      fullPath: '/casos-ddr/$id'
      preLoaderRoute: typeof LayoutCasosDdrIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/casos-ddr/$id/evaluacion': {
      id: '/_layout/casos-ddr/$id/evaluacion'
      path: '/evaluacion'
      fullPath: '/casos-ddr/$id/evaluacion'
      preLoaderRoute: typeof LayoutCasosDdrIdEvaluacionRouteImport
      parentRoute: typeof LayoutCasosDdrIdRoute
    }
  }
}

interface LayoutCasosDdrIdRouteChildren {
  LayoutCasosDdrIdEvaluacionRoute: typeof LayoutCasosDdrIdEvaluacionRoute
}

const LayoutCasosDdrIdRouteChildren: LayoutCasosDdrIdRouteChildren = {
  LayoutCasosDdrIdEvaluacionRoute: LayoutCasosDdrIdEvaluacionRoute,
}

const LayoutCasosDdrIdRouteWithChildren =
  LayoutCasosDdrIdRoute._addFileChildren(LayoutCasosDdrIdRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUsuariosRoute: typeof LayoutUsuariosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCasosDdrIdRoute: typeof LayoutCasosDdrIdRouteWithChildren
  LayoutClientesIdRoute: typeof LayoutClientesIdRoute
  LayoutKycNuevoRoute: typeof LayoutKycNuevoRoute
  LayoutCasosDdrIndexRoute: typeof LayoutCasosDdrIndexRoute
  LayoutClientesIndexRoute: typeof LayoutClientesIndexRoute
  LayoutKycIndexRoute: typeof LayoutKycIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUsuariosRoute: LayoutUsuariosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCasosDdrIdRoute: LayoutCasosDdrIdRouteWithChildren,
  LayoutClientesIdRoute: LayoutClientesIdRoute,
  LayoutKycNuevoRoute: LayoutKycNuevoRoute,
  LayoutCasosDdrIndexRoute: LayoutCasosDdrIndexRoute,
  LayoutClientesIndexRoute: LayoutClientesIndexRoute,
  LayoutKycIndexRoute: LayoutKycIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface TwoFactorRouteChildren {
  TwoFactorSetupRoute: typeof TwoFactorSetupRoute
}

const TwoFactorRouteChildren: TwoFactorRouteChildren = {
  TwoFactorSetupRoute: TwoFactorSetupRoute,
}

const TwoFactorRouteWithChildren = TwoFactorRoute._addFileChildren(
  TwoFactorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AccountLockedRoute: AccountLockedRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TwoFactorRoute: TwoFactorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
